// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Slaplist.Application.Data;

#nullable disable

namespace Slaplist.Application.Migrations
{
    [DbContext(typeof(SlaplistDbContext))]
    [Migration("20260107195258_AddDatesForStatistics")]
    partial class AddDatesForStatistics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Slaplist.Application.Domain.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReportedTrackCount")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<bool>("SyncComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LastSyncedAt");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.HasIndex("Source", "Type");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Slaplist.Application.Domain.CollectionTrack", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AddedToCollectionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("CollectionId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("CollectionTracks");
                });

            modelBuilder.Entity("Slaplist.Application.Domain.QueryStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApiFetchCalls")
                        .HasColumnType("integer");

                    b.Property<int>("ApiSearchCalls")
                        .HasColumnType("integer");

                    b.Property<int>("CacheHits")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("InputQueries")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("NotEnoughQuota")
                        .HasColumnType("integer");

                    b.Property<int>("QuotaUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("QueryStatistics");
                });

            modelBuilder.Entity("Slaplist.Application.Domain.QuotaTracker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DailyLimit")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("FetchCalls")
                        .HasColumnType("integer");

                    b.Property<int>("SearchCalls")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("UnitsUsed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Source")
                        .IsUnique();

                    b.ToTable("QuotaTrackers");
                });

            modelBuilder.Entity("Slaplist.Application.Domain.SearchCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("QuotaUsed")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<Guid>>("ResultCollectionIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<Guid>>("ResultTrackIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("SearchType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedQuery", "Source", "SearchType", "SearchedAt");

                    b.ToTable("SearchCaches");
                });

            modelBuilder.Entity("Slaplist.Application.Domain.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("BandcampUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Bpm")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscogsMasterId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DiscogsReleaseId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Key")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastEnrichedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedArtist")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.PrimitiveCollection<List<string>>("RawTitlesEncountered")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YoutubeVideoId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DiscogsReleaseId")
                        .HasFilter("\"DiscogsReleaseId\" IS NOT NULL");

                    b.HasIndex("Genre");

                    b.HasIndex("Label");

                    b.HasIndex("YoutubeVideoId")
                        .IsUnique()
                        .HasFilter("\"YoutubeVideoId\" IS NOT NULL");

                    b.HasIndex("NormalizedArtist", "NormalizedTitle");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Slaplist.Application.Domain.CollectionTrack", b =>
                {
                    b.HasOne("Slaplist.Application.Domain.Collection", "Collection")
                        .WithMany("CollectionTracks")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Slaplist.Application.Domain.Track", "Track")
                        .WithMany("CollectionTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Slaplist.Application.Domain.Collection", b =>
                {
                    b.Navigation("CollectionTracks");
                });

            modelBuilder.Entity("Slaplist.Application.Domain.Track", b =>
                {
                    b.Navigation("CollectionTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
